"""Analytics instrumentation for Surfa MCP server using surfa-ingest."""

import time
from typing import Any, Callable, TypeVar, ParamSpec
from functools import wraps
from surfa_ingest import SurfaClient, generate_session_id
from .config import get_settings

# Type variables for generic decorator
P = ParamSpec('P')
R = TypeVar('R')

# Global analytics client
_analytics_client: SurfaClient | None = None


def get_analytics_client() -> SurfaClient | None:
    """Get or create the analytics client for dogfooding."""
    global _analytics_client
    
    if _analytics_client is not None:
        return _analytics_client
    
    settings = get_settings()
    
    # Only create client if ingest key is configured
    if not settings.surfa_ingest_key:
        return None
    
    _analytics_client = SurfaClient(
        ingest_key=settings.surfa_ingest_key,
        api_url=settings.surfa_api_url,
        # session_id is auto-generated by the SDK
    )
    
    return _analytics_client


def track_tool(tool_name: str):
    """Decorator to track MCP tool execution with surfa-ingest.
    
    Usage:
        @track_tool("get_analytics")
        async def get_analytics_mcp():
            ...
    """
    def decorator(func: Callable[P, R]) -> Callable[P, R]:
        @wraps(func)
        async def wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
            analytics = get_analytics_client()
            
            # If analytics not configured, just run the function
            if analytics is None:
                return await func(*args, **kwargs)
            
            # Extract arguments for tracking
            tool_args = {}
            if args:
                # For positional args, we can't easily name them
                tool_args["args_count"] = len(args)
            if kwargs:
                # Include kwargs (filter out sensitive data if needed)
                tool_args.update({
                    k: v for k, v in kwargs.items() 
                    if v is not None and k not in ["api_key", "token"]
                })
            
            # Track tool start
            start_time = time.time()
            analytics.tool_started(
                tool_name=tool_name,
                args=tool_args
            )
            
            try:
                # Execute the tool
                result = await func(*args, **kwargs)
                
                # Track tool completion
                latency_ms = int((time.time() - start_time) * 1000)
                analytics.tool_completed(
                    tool_name=tool_name,
                    args=tool_args,
                    latency_ms=latency_ms
                )
                
                return result
                
            except Exception as e:
                # Track tool failure
                latency_ms = int((time.time() - start_time) * 1000)
                analytics.tool_failed(
                    tool_name=tool_name,
                    args=tool_args,
                    error=str(e),
                    latency_ms=latency_ms
                )
                raise
        
        return wrapper
    return decorator


def flush_analytics():
    """Flush analytics events on server shutdown."""
    if _analytics_client is not None:
        _analytics_client.flush()
